## 데이터 전처리 주요 기법
- 데이터 정제
    - 결측치, 이상치, 잡음
- 데이터 결합
- 데이터 변환
    - Nomalization, scailing
- 차원 축소
    - Feature selection
        - filter, wrapper, embedded
    - Feature extraction
        - PCA,SVD,FA,NMF


### 결측값(missing value)처리
- 해당 데이터 행을 모두 제거(완전제거법)
- 수작업으로 채워 넣음
- 특정값 사용
- 핫덱(hot-deck)대체법
    - 동일한 조사에서 다른 관측값으로부터 얻은 자료를 이용해 대체
    - 관측값 중 결측치와 비슷한 특성을 가진 것을 무작위 추출하여 대체
- 평균값 사용(전체 평균 혹은 기준 속성 평균)
    - 표준오차 과소추정 발생
- 가장 가능성이 높은 값 사용(회귀분석,보간법 등) -> 모델사용

---

### 데이터 인코딩
- 문자열을 숫자형으로 변환
- 인코딩 방식
    - 레이블 인코딩(Label encoding)
    - 원-핫 인코딩(One-hot encoding)
    
#### 레이블 인코딩(Lavel encoding)
- 문자열 데이터를 숫자로 코드화
- 범주형 자료의 수치화

#### 사이킷런의 레이블 인코딩 클래스 : LabelEncoder
1. LabelEncoder 객체 생성
2. fit()
    - 레이블 인코더를 맞춤
3. transform()
    - 인코딩된 레이블 반환

In [2]:
from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(labels)

[0 1 4 5 3 3 2 2]


LabelEncoder 객체의 classes_ : 인코딩된 문자열 값 목록 확인

In [3]:
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자렌지', '컴퓨터'], dtype='<U4')

inverse_transform() : 인코딩된 값을 다시 디코딩

In [4]:
encoder.inverse_transform([3,0,2,1])

array(['선풍기', 'TV', '믹서', '냉장고'], dtype='<U4')

- 레이블 인코딩된 데이터는 회귀와 같은 ML 알고리즘을 적용해서는 안됨

---

## 원-핫 인코딩(One-Hot encoding)
- feature 값의 유형에 따라 새로운 feature를 추가하여
- 고유 값에 해당하는 컬럼만 1을 표시하고 나머지 컬럼에는 0을 표시
- 범주형 변수를 독립변수로 갖는 회귀분석의 경우 범주형 변수를 dummy변수로 변환

**다항 회귀분석에서 각각에 대한 변수로 사용 (영향력이 어떻게 되는지)**


In [5]:
#  사이킷런에서 원-핫 인코딩 클래스 : OneHotEncoder
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
import numpy as np

items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [7]:
# 2. 2차원 데이터로 변환
labels = labels.reshape(-1,1) #( ,1) => (여러행,1컬럼)
labels

array([[0],
       [1],
       [4],
       [5],
       [3],
       [3],
       [2],
       [2]])

In [8]:
# 3. 원-핫 인코딩을 적용
one_encoder = OneHotEncoder()
one_encoder.fit(labels)
one_labels = one_encoder.transform(labels)
one_labels

<8x6 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [ ]:
# sparse matrix : 회소행렬(행렬의 값이 대부분 0인 경우)

In [9]:
print(one_labels)

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 4)	1.0
  (3, 5)	1.0
  (4, 3)	1.0
  (5, 3)	1.0
  (6, 2)	1.0
  (7, 2)	1.0


In [11]:
# 2차원 형태로 출력
one_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [13]:
# 원 - 핫 인코딩 전체 과정
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
import numpy as np

items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 1. 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# 2. 2차원 데이터로 변환
labels = labels.reshape(-1,1) #( ,1) => (여러행,1컬럼)

# 3. 원-핫 인코딩을 적용
one_encoder = OneHotEncoder()
one_encoder.fit(labels)
one_labels = one_encoder.transform(labels)

print('원-핫 인코딩 데이터')
print(one_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(one_labels.shape)


원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


## Pandas API 사용 원-핫 인코딩 수행
- get_dummies()메서드 사용
- 숫자형으로 변화없이 바로 변환

In [16]:
import pandas as pd

df = pd.DataFrame({'item':items})
df

item
0    TV
1   냉장고
2  전자렌지
3   컴퓨터
4   선풍기
5   선풍기
6    믹서
7    믹서

In [17]:
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자렌지  item_컴퓨터
0        1         0        0         0          0         0
1        0         1        0         0          0         0
2        0         0        0         0          1         0
3        0         0        0         0          0         1
4        0         0        0         1          0         0
5        0         0        0         1          0         0
6        0         0        1         0          0         0
7        0         0        1         0          0         0

In [18]:
# Pandas 데이터프레임을 NumPy 배열로 변환
pd.get_dummies(df).to_numpy()

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]], dtype=uint8)

---

## 피처 스케일링과 정규화
- 피처 스케일링(feature scailing)
    - 서로 다른 변수의 값 범위를 일정한 수준으로 맟춤
- 방식
    - Z-scailing
        - 표준화
        - 평균이 0이고 분산이 1인 가우시안 정규분포로 변환
        - 정규화
        - sklearn.preprocessing의 StandardScaler 모듈
    - min-max
        - 0~1로 변환
        - sklearn.preprocessing의 MinMaxScaker 모듈

### 정규화
- 단위 차이, 극단값 등으로 비교가 어렵거나 왜곡이 발생할 때, 표준화하여 비교 가능하게 만드는 방법
- scale이 다른 여러 변수에 대해 Scale을 맞춰 모든 데이터 포인트가 동일한 정도의 중요도로 비교되도록 함

In [22]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(iris_data, columns=iris.feature_names)

print(iris_df.mean())
print(iris_df.std())

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
sepal length (cm)    0.828066
sepal width (cm)     0.435866
petal length (cm)    1.765298
petal width (cm)     0.762238
dtype: float64


### StandardScaler이용 표준화해서 변환
1. StandardScaler 객체 생성
2. fit() : 데이터 변환을 위한 기준 정보 설정
3. transform() : fit()에서 설정된 정보를 이용해 데이터 변환
    - scale 변환된 데이터 셋이 numpy ndarray로 반환

In [26]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
# print(iris_scaled)

iris_scaled_df = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print(iris_scaled_df.mean())
print(iris_scaled_df.std())

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.00335
sepal width (cm)     1.00335
petal length (cm)    1.00335
petal width (cm)     1.00335
dtype: float64


### MinMaxScaler 이용 변환
1. MinMaxScaler 객체생성
2. fit()
3. transform() : scale 변환된 데이터 셋이 numpy ndarray로 반환

In [27]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
# print(iris_scaled)

iris_scaled_df = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print(iris_scaled_df.min())
print(iris_scaled_df.max())


sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


## 데이터 변환

데이터 변환 목적
- 분포의 대칭화
- 산포를 비슷하게
- 변수 간의 관계를 단순하게 하기 위해

데이터 변환 종류
- 모양 변환 : pivot, unpivot
- 파생변수/요약변수
- 데이터 분포의 변환
    - 데이터가 정규분포를 따르지 않을 경우, 정규분포 혹은 정규분포에 가깝게 변환하는 기법
    - 정규분포를 기준으로 치우침 정도(왜도)   
    Positively Skewed / negatively Skewed 
- 데이터 분포 변환 : 제곱근변환, 제곱변환, 로그변환
    